/*
 * This source file was generated by the Gradle 'init' task
 */
package tree.mobile.legends;

import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testApp() {
        assertTrue(true);
    }
}
