/*
 * This source file was generated by the Gradle 'init' task
 */
package tree.mobile.legends;


import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import tree.mobile.legends.ItemMLBB.ItemNode;
import tree.mobile.legends.TREEMLBB.TreeMlBB;

public class App {
    public static void main(String[] args) {

        // Create sample item tree
        ItemNode root = new ItemNode("Malefic Gun", "Item utama");//root

        ItemNode leftItem = new ItemNode("Fury Hammer", "Item kedua");
        ItemNode rightItem = new ItemNode("Knife", "Item ketiga");
        ItemNode bottomItem = new ItemNode("Knife", "Item keempat");

        root.addChild(leftItem);
        root.addChild(rightItem);
        root.addChild(bottomItem);

        ItemNode dagger = new ItemNode("Dagger", "Item terakir");
        leftItem.addChild(dagger);

        // Print the tree structure
        System.out.println("=== Item Build Tree ===");
        TreeMlBB.printTree(root, 0);

        
        // Print all build paths
        System.out.println("\n=== All Build Paths ===");
        TreeMlBB.printAllBuildPaths(root, new ArrayList<>());

        System.out.println("\n=== COUNT ITEM ===");
        int count = TreeMlBB.countItemOccurrences(root, "Knife");
        System.out.println("Knife muncul: " + count + " kali");

        // Count nodes and leaves, height of the tree
        System.out.println("\nTotal Nodes: " + TreeMlBB.countNodes(root));
        System.out.println("Total Leaves: " + TreeMlBB.countLeaves(root));
        System.out.println("Tree Height: " + TreeMlBB.height(root));

        // Find path to a specific item
        Scanner sc = new Scanner(System.in);
        System.out.print("\nMasukkan nama item: ");
        String targetItem = sc.nextLine();

        System.out.println("\n=== Path to '" + targetItem + "' ===");
        TreeMlBB.printPathToTarget(root, targetItem, new ArrayList<>());

        // Count occurrences of a specific item
        int result = TreeMlBB.countItemOccurrences(root, targetItem);
        System.out.println("Item '" + targetItem + "' muncul: " + result + " kali");
        // find path to a specific item
        List<String> path = new ArrayList<>();
        if (TreeMlBB.findPath(root, targetItem, path)) {
            System.out.println("Path: " + String.join(" -> ", path));
        } else {
            System.out.println("Item tidak ditemukan.");
        }
        
    }
}
